# Generated by Django 3.1.3 on 2020-11-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='customer',
        ),
    ]
