# Generated by Django 3.1.3 on 2020-11-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_files_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='FileUpload',
        ),
    ]
